name: Haskell CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install latest ghcup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

    - name: Setup Haskell environment
      run: |
        source ~/.ghcup/env
        ghcup upgrade
        ghcup install ghc 9.4.7
        ghcup set ghc 9.4.7
        ghc --version
        
    - name: Build and Test with Stack
      run: |
        stack setup
        stack build --test --no-terminal --bench --only-dependencies
        stack test
